#!/usr/bin/env bash
#running, and listening on port 80 of all the server’s active IPv4 IPs
sed -i "s/8080/80/" /etc/nginx/sites-enabled/default
service nginx restart
kill "$(pgrep 'nginx' | head -1)”
